# Generated by Django 2.2 on 2019-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_auto_20190519_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
