# Generated by Django 2.2.1 on 2019-05-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190511_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fk_attachments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.Attachment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fk_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priorities', to='tickets.Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fk_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_list', to='tickets.Status'),
        ),
    ]
