# Generated by Django 2.2.1 on 2019-05-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190511_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fk_attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.Attachment'),
        ),
    ]
