# Generated by Django 2.2 on 2019-05-20 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
