# Generated by Django 2.2 on 2019-05-20 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0002_auto_20190519_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
